### ISSUE TITLE
GoodJob but ummm

### ISSUE THREAD

**Issue by wendellmeset** [Python-22/Cracked-Qlutch#2]
So good job with cracking/deobfuscating qlutch, but I was wondering if you would mind putting this cracked qlutch in a plugin? Since I just don't have the time to extract allllllll the code and put it in another plugin and fix all the errors, so can you please stick this in an actual jar that's compiled and stuff and put that in releases, thanks a lot, if you do this, I might buy your custom $10 backdoor do the injection feature if you would do this for me, ty (oh and make sure its a working Minecraft plugin that I can use qlutch and everything, remember the prefix for the qlutch commands too)

**Comment by Python-22** [comment]
i will once im done kego i will remove licensing system and add to plugin with no auth
