### ISSUE TITLE
May I Please Have Qlutch Cracked

### ISSUE THREAD

**Issue by NotAiTristanAlt** [Python-22/Cracked-Qlutch#3]
I saw in another issue that you are fixing it up so we can login without buying qlutch, instead of plain code cracked, May you please put it in releases tab or give it to me personally, If you would mind. I found you on leakmania, and I would happily buy Kego if I get Qlutch Crack and it works. Thanks You! 🥺😊

**Comment by Python-22** [comment]
feel free to join discord since not everyones getting it
